docs/getting_started/kubernetes_on_ubuntu_machine.md
Update microk8s local-storage save path customization
=> Add local-storage path customization

docs/model-deployment-tutorial-package-image.md, docs/zh-tw/model-deployment-tutorial-package-image.md, website/sidebars.json
Add model deployment tutorial: package image
Signed-off-by: Jack Pan <jackpan@infuseai.io>
=> Add model deployment tutorial: package image

docs/model-deployment-tutorial-package-image.md, docs/zh-tw/model-deployment-tutorial-package-image.md
=> Update the model image package doc

docs/design/job-submission.md
Update design doc of job submission for workingdir path changes
Signed-off-by: Jack Pan <jackpan@infuseai.io>
=> Update design doc of job submission for workingdir path changes

docs/model-deployment-tutorial-prepackage-image.md, docs/zh-tw/model-deployment-tutorial-prepackage-image.md, website/sidebars.json
Signed-off-by: Jack Pan <jackpan@infuseai.io>
=> Add tensorflow2 prepackage doc

docs/getting_started/kubernetes_on_eks.md
=> update eks docs

docs/getting_started/install_keycloak.md, website/versioned_docs/version-2.5/getting_started/install_keycloak.md, website/versioned_docs/version-2.6/getting_started/install_keycloak.md
=> [fix] change to use new keycloak helm chart

docs/tasks/non-standard-image.md, website/sidebars.json
add notes for non standard images
=> Update non-standard images supporting

docs/design/model-deployment.md
Add model deployment endpoint/clients design doc
=> Add model deployment endpoint/clients design doc

docs/model-deployment.md, docs/zh-tw/model-deployment.md
Signed-off-by: ChanYiLin <j5111261112@gmail.com>
Signed-off-by: Jack Lin <chanyi.jack.lin@infuseai.io>
=> add doc for getting the client name in the predict function

docs/references/dotenv.md, docs/references/feature-flag.md, docs/references/primehub_chart.md
=> MinIO installation

docs/getting_started/kubernetes_on_ubuntu_machine.md
* Make install easy with helper scripts
* Notes for Troubleshooting
=> Update singlenode installation

docs/assets/cluster-autoscaler-autodiscover.yaml.tmpl, docs/getting_started/install_helper.md, docs/getting_started/kubernetes_on_eks.md
=> [Feature] Update AWS EKS setup document with autoscaler config

docs/references/dotenv.md, docs/references/primehub_chart.md, docs/tasks/minio-configuration.md, website/sidebars.json
* value file example
* add helper envs
=> Document how to configure minio and minio

docs/zh-tw/job-submission-cht.md
=> Update translation in job-submission-cht.md

docs/zh-tw/job-submission-cht.md
=> Fix path in job-submission-cht.md

docs/tasks/minio-configuration.md
Signed-off-by: popcorny <celu@infuseai.io>
=> minio configuration for ceph rgw

docs/getting_started/kubernetes_on_eks.md
=> [Fix] fix aws eks autoscaler yaml url

docs/getting_started/install_primehub.md, docs/getting_started/kubernetes_on_eks.md, docs/getting_started/kubernetes_on_gke.md, docs/getting_started/prerequisites.md
Modified the Helm command and parameters for Helm3.
=> Changed to use Helm3 command and corresponding parameters.

docs/getting_started/configure-job-submission.md
Signed-off-by: Jack Pan <jackpan@infuseai.io>
=> Add clean up completed jobs config doc

docs/model-deployment-tutorial-prepackage-image.md
=> update prepackage image doc

docs/guide_manual/images-list.md, docs/zh-tw/guide_manual/images-list.md
Signed-off-by: Aaron Huang <aaroms9733@gmail.com>
=> Update image list for new tf 2.3.1 and pytorch 1.7

docs/getting_started/configure-job-submission.md, website/versioned_docs/version-3.1/getting_started/configure-job-submission.md
=> [Fix] ch13416 change default value of jobLimit

docs/design/model-deployment.md
Update the design document for model uri
https://app.clubhouse.io/infuseai/story/13134/design-document-for-model-file-support
=> Update model deployment design document for model uri

docs/model-deployment.md, docs/zh-tw/model-deployment.md
Co-authored-by: Timothy Lee <ctiml@infuseai.io>
=> change model deployment to beta tag

docs/guide_manual/images-list.md, docs/zh-tw/guide_manual/images-list.md
Signed-off-by: Aaron Huang <aaroms9733@gmail.com>
=> Update image list for new tf 2.2 image

docs/guide_manual/images-list.md, docs/zh-tw/guide_manual/images-list.md
=> [Fix] Fix typo on image list

docs/model-deployment-prepackaged-server-tensorflow2.md, docs/model-deployment-tutorial-model-image.md, docs/model-deployment-tutorial-prepackaged-image-phfs.md
=> model tutorial: add tf2 image input doc

docs/tasks/job-runtime-customization.md, website/sidebars.json
write a job runtime customization task
=> Add job runtime customization

docs/tasks/job-runtime-customization.md
=> remove phfs from custom runtime doc

docs/references/primehub_chart.md
=> dataset upload and phfs upload use the same tus image

docs/design/image-builder.md, docs/getting_started/configure-image-builder.md, website/sidebars.json
=> [Feature] ch14899 add configure package of image builder

docs/model-deployment-prepackaged-server-tensorflow2.md
=> update tensorflow model doc

docs/guide_manual/images-list.md
=> [Update] support images list

docs/model-deployment-prepackaged-server-pytorch.md, docs/model-deployment-prepackaged-server-tensorflow2.md
=> update tf2 and pytorch docs to use dockerfile

docs/environment-variables.md, website/sidebars.json
Story details: https://app.clubhouse.io/infuseai/story/15692
=> Provide environment document in primehub site

docs/tasks/monitoring.md
=> Update oidc url

Dockerfile
=> upgrade version

docs/tasks/monitoring.md
Signed-off-by: Ching Yi, Chan <qrtt1@infuseai.io>
=> fix wrong grafana url

docs/tasks/monitoring.md
Signed-off-by: Even Wei <evenwei@infuseai.io>
Co-author: Poga <poga@infuseai.io>
=> Update Grafana PrimeHub dashboard 

docs/guide_manual/images-list.md
=> [Feature] ch16290 add image of tf v2.4 and pyTorch 1.7 with cuda 11

docs/primehub-app.md
Signed-off-by: Even Wei <evenwei@infuseai.io>
=> Add preset environment variables

docs/guide_manual/images-list.md
Update notebook images tags, which supports MLflow and boto3.
=> Update notebook image tags

docs/comparison.md
Signed-off-by: Ash Wu <hSATAC@gmail.com>
=> Fix feature comparison table

docs/comparison.md, docs/model-deployment-prepackaged-server-tensorflow2.md, docs/primehub-app.md, docs/quickstart/login-portal-user.md, docs/zh-tw/model-deployment-prepackaged-server-tensorflow2-cht.md, docs/zh-tw/primehub-app-cht.md, docs/zh-tw/quickstart/login-portal-user.md
=> support mlflow autolog model

docs/guide_manual/images-list.md, docs/zh-tw/guide_manual/images-list.md
1. Update PyTorch image tags
2. Sync zh-tw version
=> Update fixed pytorch image tags

docs/model-deployment-prepackaged-server-pytorch.md
=> add support of mlflow autolog model

docs/model-deployment-prepackaged-server-sklearn.md
Signed-off-by: Ching Yi, Chan <qrtt1@infuseai.io>
=> update sklearn server

docs/model-deployment-model-uri.md
docs `nfs://` in the Model URI
=> Add nfs:// support

docs/guide_manual/images-list.md
Update available image list with
- MLflow 1.18.0
- TensorFlow 2.5.0
- PyTorch 1.8.0
=> Update available image list

docs/getting_started/configure-image-builder.md, website/versioned_docs/version-3.4/getting_started/configure-image-builder.md
=> [Update] ch18448 update image builder document to support AWS ECR

docs/guide_manual/admin-nb-admin.md, website/versioned_docs/version-3.5/guide_manual/admin-nb-admin.md
Signed-off-by: Eric Chang <ericcc@infuseai.io>
=> Fix typo in admin notebook admin

docs/primehub-app.md
=> PH Application: some access scopes are EE-only

docs/primehub-end-to-end.md
Signed-off-by: Even Wei <evenwei@infuseai.io>
=> Improve prerequisite of end-to-end tutorial

docs/getting_started/kubernetes_on_eks.md
=> [Update] AWS EKS nginx-ingress installation document

docs/getting_started/kubernetes_on_ubuntu_ce.md, docs/getting_started/kubernetes_on_ubuntu_machine.md, docs/getting_started/prerequisites.md, website/versioned_docs/version-3.6/getting_started/prerequisites.md
What added:
- add cURL onto prereq and related doc. (version: 3.6, next)
=> Update curl onto prerequisites for installation

.gitignore, docs/getting_started/install_primehub_ce.md, docs/getting_started/kubernetes_on_ubuntu_ce.md, docs/getting_started/prerequisites.md, website/versioned_docs/version-3.6/getting_started/kubernetes_on_ubuntu_ce.md
1. Add: Prereq git section
2. Update: CE Multinode, Singlenode, Prereq domain name
3. Update git ignore
Note: will update EE with another PR.
cc @gblpedia and @kentwelcome for reviewing.
=> Update ce installation and prereq

docs/guide_manual/admin-system.md
Signed-off-by: Eric Chang <ericcc@infuseai.io>
** PR checklist **
**What type of PR is this?**
Chore
**What this PR does / why we need it**:
Correct errors
**Which issue(s) this PR fixes**:
Add deploy to System Settings; Correct capitalization
**Special notes for your reviewer**:
**Does this PR introduce a user-facing change?**:
```release-note
NONE
```
=> Add deploy to System Settings; Correct capitalization

docs/getting_started/configure-image-builder.md
Signed-off-by: Timothy Lee <ctiml@infuseai.io>
Co-authored-by: Ash Wu <hsatac@infuseai.io>
=> Image builder supports single repository

docs/comparison.md, docs/license-comparison.md, website/sidebars.json, website/static/css/custom.css
=> update feature comparison and add license comparison

docs/quickstart/assign-group-admin.md
Small changes to the Assign Group Admin page
=> Assign Group Admin updates - testing pull request

docs/guide_manual/images-list.md
=> update image tags

docs/primehub-app-tutorial-template.md
Signed-off-by: Timothy Lee <ctiml@infuseai.io>
Co-authored-by: Ash Wu <hsatac@infuseai.io>
=> Update docs for supporting initContainer

docs/quickstart/nb-data-store.md
Modify the persistence page, adding mount point information
=> Update the document for storage mount points

docs/primehub-end-to-end-tutorial-1.md
Default credential instructions added to End to End 1
=> added Label Studio default credentials to End to End 1

docs/quickstart/create-user.md
Updated some language in Quickstart Create User
=> Small updates to Quickstart Create User

docs/quickstart/create-group.md
Updated Quickstart - Create Group
=> Edit to introduction and clarify instructions

docs/job-submission.md
Signed-off-by: Poga Po <poga@infuseai.io>
=> tweak the description of limitations on Job submissions

docs/getting_started/prerequisites.md, website/versioned_docs/version-3.8/getting_started/prerequisites.md
Updated the prerequisites doc of PrimeHub Installation by the dependency of primehbu-install script accordingly.
Including k8s version, helm version, kubectl version
=> Updated the prerequisites of primehub installation by the

docs/comparison.md, docs/primehub-app.md, docs/zh-tw/primehub-app-cht.md
Signed-off-by: Aaron Huang <aaroms9733@gmail.com>
=> App feature GA

website/versioned_docs/version-3.9/comparison.md, website/versioned_docs/version-3.9/primehub-app.md, website/versioned_docs/version-3.9/zh-tw/primehub-app-cht.md
=> backport phapps GA to v3.9

docs/guide_manual/images-list.md
=> Patch tensorboard fixes to TF 2.4 - update image tag

docs/getting_started/configure-ssh-server.md
Signed-off-by: Timothy Lee <ctiml@infuseai.io>
=> Add SSH bastion server configuration

website/versioned_docs/version-3.10/getting_started/prerequisites.md
Signed-off-by: eric yang <ericy@infuseai.io>
=> update prerequisites to indicate the supported k8s versions

website/versioned_docs/version-3.10/getting_started/kubernetes_on_ubuntu_ce.md, website/versioned_docs/version-3.10/getting_started/kubernetes_on_ubuntu_machine.md
Updates the 3.10 (current) docs
=> k8s bump on 3.10 docs

docs/guide_manual/custom-image-guideline.md, website/versioned_docs/version-3.10/guide_manual/custom-image-guideline.md
Removed table, and added short sentence with link to available images.
=> Removed out-of-date table, added link to Available Images list

website/versioned_docs/version-3.11/model-deployment.md
=> add explanation and suggestion about deployment status

website/versioned_docs/version-3.11/guide_manual/images-list.md
=> bump tf and pytorch images

website/versioned_docs/version-3.12/comparison.md
Fix this page error: https://docs.primehub.io/docs/comparison
=> Fix deployment information error.

website/versioned_docs/version-3.12/comparison.md
Fix this error: https://docs.primehub.io/docs/comparison
=> Fix comparison error.

website/versioned_docs/version-3.10/comparison.md, website/versioned_docs/version-3.11/comparison.md, website/versioned_docs/version-3.8/comparison.md, website/versioned_docs/version-3.9/comparison.md
Signed-off-by: Dennis Huang haicha.tw@gmail.com
PrimeHub doc site correction: Correct the contents of the "Tiers Feature Comparison" page in previous versions.
PR checklist
What type of PR is this?
bug
What this PR does / why we need it:
Correct the contents of the "Tiers Feature Comparison" pages in previous versions.
Which issue(s) this PR fixes:
N/A
Special notes for your reviewer:
N/A
Does this PR introduce a user-facing change?:
NONE
Assignees
@huaichehuang
=> Correct the contents of the "Tiers Feature Comparison" pages in previous versions.
